# Generated by Django 2.2.4 on 2020-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0002_auto_20200724_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
