# Generated by Django 2.2.4 on 2020-07-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0003_wishmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishManager',
        ),
    ]
