# Generated by Django 2.2.4 on 2020-07-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0004_delete_wishmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='item',
            new_name='wish',
        ),
    ]
