# Generated by Django 2.2.4 on 2020-07-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0005_auto_20200724_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
